### ISSUE TITLE
Overridden namescape

### ISSUE THREAD

**Issue by diegoleme** [lazd/gulp-handlebars#56]
I have the files:

templates/projects/list.actions.bhs
templates/projects/list.hbs
templates/projects/list.item.hbs

They are loaded in that order by alphabetical order.

The App.projects.list.actions is create, but is overridden by App.projects.list

**Comment by lazd** [comment]
Without your gulpfile, I can't help you.

**Comment by diegoleme** [comment]
Tks @lazd

Templates task:
```
gulp.task('templates',function(){
  gulp.src('./app/templates/**/*.hbs')
    .pipe(handlebars())
    .pipe(wrap('Handlebars.template(<%= contents %>)'))
    .pipe(declare({
      namespace: 'App.Templates',
      noRedeclare: true
    }))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('./dist/js/'))
})
```
If you need more information, let me know

**Comment by lazd** [comment]
Can you paste the compiled output where it overwrites stuff?

**Comment by lazd** [comment]
@diegoleme, I don't think you should have an overriding problem based on the way `nsdeclare` works -- it always uses the existing item instead of defining over the top of something. You will have properties on your function objects for the nested items, but it should never override. Can you put the `templates.js` file it generates in a Gist and link to it from here? I'll take a look.

**Comment by diegoleme** [comment]
I'm trying to do a test to reproduce the error

**Comment by diegoleme** [comment]
@lazd look this branch please: https://github.com/diegoleme/gulp-handlebars/tree/fix-override-template

**Comment by lazd** [comment]
Thanks for the detailed test case, I see the error. This bug is actually with `gulp-declare`, not `gulp-handlebars`. Because the files in the stream come in the order:

* Basic.a.hbs
* Basic.hbs
* Basic.b.hbs

`gulp-declare` will first declare the namespace for `Templates.Basic`, then assign `Templates.Basic.a` to the template. Then, it will see `Basic` and assign `Templates.Basic` to the template. Then it will get `Basic.b` and assign `Templates.Basic.b` to the template.

Short of adding another plugin inline that orders files by the number of dots in themI don't know how to solve this... I'll think on it some more.

**Comment by diegoleme** [comment]
For now I decided that way, but it is an ugly hack:

Renamed Basic.hbs to Basic._.hbs, and include processName method

gulp.task('templates',function(){
  gulp.src('./app/templates/**/*.hbs')
    .pipe(handlebars())
    .pipe(wrap('Handlebars.template(<%= contents %>)'))
    .pipe(declare({
      namespace: 'App.Templates',
      noRedeclare: true,
      processName: function(filePath) {
          return declare.processNameByPath(
            filePath.replace('_', '')
          )
        }
    }))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('./dist/js/'))
})

**Comment by lazd** [comment]
Closing as this issue relates to `gulp-declare`.
